# Dots are nodes.
# They have a DOMElement attached to them by default.

Dot = (step) ->
  Node.call this
  # Center dot.
  @setOrigin(0.5, 0.5, 0.5).setMountPoint(0.5, 0.5, 0.5).setAlign(0.5, 0.5, 0.5).setSizeMode('absolute', 'absolute', 'absolute').setAbsoluteSize DOT_SIZE, DOT_SIZE, DOT_SIZE
  # Add the DOMElement (DOMElements are components).
  @el = new DOMElement(this, properties:
    background: 'blue'
    borderRadius: '100%')
  # Add the Position component.
  # The position component allows us to transition between different states
  # instead of instantly setting the final translation.
  # this.position = new Position(this);
  return

'use strict'
famous = require('famous')
DOMElement = famous.domRenderables.DOMElement
FamousEngine = famous.core.FamousEngine
Node = famous.core.Node
clock = FamousEngine.getClock()
DOT_SIZE = 200
# Boilerplate
FamousEngine.init()
scene = FamousEngine.createScene()
Dot.prototype = Object.create(Node.prototype)
Dot::constructor = Dot
dot = new Dot
scene.addChild dot
dotScale = new (famous.components.Scale)(dot)
dotScale.set 0.1, 0.1, 0.1
clock.setTimeout (->
  dotScale.set 1, 1, 1, duration: 4000
  return
), 500

# ---
# generated by js2coffee 2.0.4
